### ISSUE TITLE
When showing the view initially the search bar is not visible until around 1 second later it pops in out of nowhere.

### ISSUE THREAD

**Issue by FUNKYJASPER2** [thislooksfun/SwiftlySearch#14] opened 2021-03-10 05:53 UTC

**Comment by thislooksfun** [comment] 2021-03-10 06:51
Duplicate of #8. This is the annoying and hard-to-fix behavior I mention [here](https://github.com/thislooksfun/SwiftlySearch/issues/8#issuecomment-787622895).

**Closed by thislooksfun** 2021-03-10 06:51 UTC
Labels: bug
